server:
  port: 9090
spring:
  cloud:
    openfeign:
      oauth2:
        enabled: true
        registrationClientId: taco-admin-client
  security:
    oauth2:
      client:
        provider:
          tacocloud:
            authorizationUri: http://authserver:9000/oauth2/authorize
            tokenUri: http://authserver:9000/oauth2/token
            userInfoUri: http://authserver:9000/userinfo
            jwkSetUri: http://authserver:9000/oauth2/jwks
            userNameAttribute: sub
        registration:
          taco-admin-client:
            provider: tacocloud
            clientId: taco-admin-client
            clientSecret: secret
            authorizationGrantType: authorization_code
            redirectUri: "http://localhost:9090/login/oauth2/code/taco-admin-client"
            scope: writeIngredients,deleteIngredients,openid,profile